#!/bin/sh
for ARG in $*; do
	echo ""
	echo "###############################"
	echo "### $ARG"
	echo "###############################"
	curl -Ikvs -w "%{http_code} %{url_effective}\\n" -o /dev/null $ARG
done

