#!/bin/bash

servers=()
servers+=("pool.sks-keyservers.net")
servers+=("keys.gnupg.net")
servers+=("pgp.mit.edu")
servers+=("pgp.uni-mainz.de")

echo "We use those servers: "
for i in ${!servers[@]}; do
  echo "* ${servers[$i]}"
done

echo
echo "Pulling ${1}"
for i in ${!servers[@]}; do
  gpg --keyserver ${servers[$i]} --recv-keys ${1}
done

echo
echo "Pushing ${1}"
for i in ${!servers[@]}; do
  gpg --keyserver ${servers[$i]} --send-key ${1}
done

