#!/bin/bash

servers=()
servers+=("http://pool.sks-keyservers.net")
servers+=("http://keys.gnupg.net")
servers+=("http://pgp.mit.edu")
servers+=("http://pgp.uni-mainz.de")
servers+=("http://keyserver.opensuse.org")
servers+=("https://keyserver.ubuntu.com")
servers+=("https://pgp.key-server.io")
servers+=("https://keys.openpgp.org")

echo "We use those servers: "
for i in ${!servers[@]}; do
  echo "* ${servers[$i]}"
done

echo
echo "Pulling ${1}"
for i in ${!servers[@]}; do
  gpg --keyserver ${servers[$i]} --recv-keys ${1}
done

echo
echo "Pushing ${1}"
for i in ${!servers[@]}; do
  gpg --keyserver ${servers[$i]} --send-key ${1}
done

