#!/usr/bin/env bash

while [ "$1" != "" ]; do
  case $1 in
    "start" ) echo "Starting..."
              gpg-agent --daemon --write-env-file "${HOME}/.gpg-agent-info"
              ;;

    "load" )  echo "Loading..."
              if [ -f "${HOME}/.gpg-agent-info" ]; then
                . "${HOME}/.gpg-agent-info"
                export GPG_AGENT_INFO
                export SSH_AUTH_SOCK
              fi

              GPG_TTY=$(tty)
              export GPG_TTY
              ;;

    * )       echo "Use 'start' or 'load' ..."
              exit 1
  esac
  shift
done

