#!/bin/sh
if [ $1 ]; then
	nmap -p 21,22,80,445 -PE $1 2>/dev/null -oG - | grep "Up$" | sed 's/Host: //' | gsed 's/ (/\t/' | sed 's/).*//'
else
	echo "Please specify network ... e.g: 192.168.1.0/24"
fi

