#!/bin/sh

USERAGENT="Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"

if [ -z "$1" ]; then
  echo "Usage: spycurl URL [METHOD DATA]"
else
  if [ -z "$2" ]; then
    METHOD="GET"
  else
    METHOD="$2"
  fi
  DATA="$3"

  curl -SLivs4 -o /dev/null -A "$USERAGENT" -X "$METHOD" -d "$DATA" "$1" \
-w "IPv4 Summary:
Total: %{time_total}s Resoling: %{time_namelookup}s Connect: %{time_namelookup}s Redirect: %{time_redirect}s
From: %{local_ip}:%{local_port} To: %{remote_ip}:%{remote_port}
$METHOD $1 $DATA
GOT %{http_code} %{url_effective}\n"
fi

