#!/usr/bin/env bash
fping -4 -c 1 $1 &> /dev/null && IP4="IPv4: ✓`ping -c 1 $1 | sed '$!d;s|.*/\([0-9.]*\)/.*|\1|' | xargs printf '%.*f\n' 0`ms   " || IP4="IPv4: ✕   "
fping -6 -c 1 $1 &> /dev/null && IP6="IPv6: ✓`ping6 -c 1 $1 | sed '$!d;s|.*/\([0-9.]*\)/.*|\1|' | xargs printf '%.*f\n' 0`ms   " || IP6="IPv6: ✕   "
echo "${IP6:0:12}${IP4:0:12}"
